/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jmate_lang_MateRuntime */

#ifndef _Included_jmate_lang_MateRuntime
#define _Included_jmate_lang_MateRuntime
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jmate_lang_MateRuntime
 * Method:    getCurrentHeapSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jmate_lang_MateRuntime_getCurrentHeapSize
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
